export const config = {
   baseURL: "http://localhost:3333",
   matrizes: [
      { ano: "2015/1", cargaHoraria: "200"},
      { ano: "2019/1", cargaHoraria: "150"}
    ],
   referencia: [
   {titulo: `Participação com aproveitamento em cursos de línguas`, modulo : 'I'},
   {titulo: `Participação como integrante em atividades artísticas e culturais`, modulo : 'I'},
   {titulo:`Participação como telespectador em atividades artísticas e culturais`, modulo : 'I'},
   {titulo:`Participação como membro em atividades esportivas`, modulo : 'I'},
   {titulo: `Participação na organização de exposições e eventos artísticos e/ou culturais`, modulo : 'I'},
   {titulo:`Participação como expositor em eventos artísticos e/ou culturais`, modulo : 'I'},
   {titulo:`Participação em cursos extracurriculares não correlatos ao curso`, modulo : 'I'},
   {titulo: `Participação/Exercício de outra atividade aprovada pelo colegiado do curso`, modulo : 'I'},
   {titulo:`Atuação como instrutor em palestras técnicas, seminários, grupos de estudos, cursos da área específica de formação, desde que não remunerados e de interesse da sociedade`, modulo : 'II'},
   {titulo: `Participação em atividades beneficentes e/ou voluntárias e em campanhas de ação social`, modulo : 'II'},
   {titulo: `Participação, com indicação formal da UEG, em diretórios acadêmicos, centros acadêmicos, entidades de classe, conselhos, comissões e colegiados internos`, modulo : 'II'},
   {titulo: `Participação em projetos de extensão vinculados à Pró-Reitoria de Extensão, Cultura e Assuntos Estudantis da UEG`, modulo : 'II'},
   {titulo: `Participação em eventos ou trabalhos convocados pela Justiça`, modulo : 'II'},
   {titulo: `Doação de sangue`, modulo : 'II'},
   {titulo: `Participação/Exercício de outra atividade aprovada pelo colegiado do curso`, modulo : 'II'},
   {titulo:  `Realização de estágio supervisionado não obrigatório na área do curso`, modulo : 'III'},
   {titulo: `Participação com aproveitamento em outros cursos e minicursos científicos ou de gestão na área de formação`, modulo : 'III'},
   {titulo: `Participação em cursos extracurriculares na área do curso ou áreas correlatas`, modulo : 'III'},
   {titulo: `Participação como apresentador de trabalhos em palestras, congressos e seminários técnico-científicos`, modulo : 'III'},
   {titulo: `Participação em atividades técnico-científicas, desde que não sejam contadas como carga horária das disciplinas ou outro componente da matriz curricular do curso`, modulo : 'III'},
   {titulo: `Participação como ouvinte em bancas de dissertação, tese`, modulo : 'III'},
   {titulo: `Participação em centros de estudos, ensino e pesquisa`, modulo : 'III'},
   {titulo:`Participação em atividades de empresa júnior`, modulo : 'III'},
   {titulo: `Participação em exposições técnico-científicas`, modulo : 'III'},
   {titulo: `Participação em atividades de incubadora tecnológica ou de empresas`, modulo : 'III'},
   {titulo:`Participação em atividades de laboratórios`, modulo : 'III'},
   {titulo: `Participação em atividades de monitoria`, modulo : 'III'},
   {titulo:`Participação em palestras, congressos, seminários técnico-científicos, semanas comemorativas e/ou oficinas`, modulo : 'III'},
   {titulo:`Participação em projetos de pesquisa, de iniciação científica e tecnológica relacionados com os objetivos do curso`, modulo : 'III'},
   {titulo:`Participação na organização de exposições e seminários de caráter acadêmico-científico`, modulo : 'III'},
   {titulo:`Organização de livro e revista ou de periódicos científicos de abrangência local, regional, nacional ou internacional`, modulo : 'III'},
   {titulo:`Publicação em revista, livro, capítulo de livro, em anais de eventos técnico-científicos ou em periódicos científicos de abrangência local, regional, nacional ou internacional`, modulo : 'III'},
   {titulo: `Participação/Exercício de outra atividade aprovada pelo colegiado do curso`, modulo : 'III'}]
}